name: movieflix
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  easy_localization: ^3.0.3
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  carousel_slider: ^4.2.1
  google_fonts: ^6.1.0
  http: ^1.1.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  youtube_player_flutter: ^8.1.2
  bloc: ^8.1.2
  meta: ^1.9.1
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  firebase_core: ^2.23.0
  firebase_auth: ^4.14.0
  retrofit: '>=4.0.0 <5.0.0'
  logger: any  #for logging purpose
  json_annotation: ^4.8.1
  dio: ^5.3.3
  freezed_annotation: ^2.4.1
  shared_preferences: ^2.2.2
  google_sign_in: ^6.1.6
  cloud_firestore: ^4.13.2
  email_validator: ^2.1.17
  flutter_slidable: ^3.0.1
  

 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  retrofit_generator: '>=7.0.0 <8.0.0'   
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  freezed: ^2.4.5
  

flutter:
  uses-material-design: true
  assets: 
    - assets/
    - assets/translations/
