// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm9As9CTEsyFbaoWLAA5KK_L19eZp_AAA',
    appId: '1:37606563236:web:8f24e6c7f11f18761bf531',
    messagingSenderId: '37606563236',
    projectId: 'movieflix-dc21d',
    authDomain: 'movieflix-dc21d.firebaseapp.com',
    storageBucket: 'movieflix-dc21d.appspot.com',
    measurementId: 'G-VNS4BWG6RL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpz7ZpA4up8H3_okOl9Jxk5KWYkgix9TE',
    appId: '1:37606563236:android:74133fd95f13aacf1bf531',
    messagingSenderId: '37606563236',
    projectId: 'movieflix-dc21d',
    storageBucket: 'movieflix-dc21d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDX2uyAb4Vn1wG4jPpZWLEkDO51jZgtm0k',
    appId: '1:37606563236:ios:25e1e918c597c1c91bf531',
    messagingSenderId: '37606563236',
    projectId: 'movieflix-dc21d',
    storageBucket: 'movieflix-dc21d.appspot.com',
    iosClientId: '37606563236-1n92q83ejccp9bv00o0qf9g5ssvbgjrn.apps.googleusercontent.com',
    iosBundleId: 'com.example.movieflix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDX2uyAb4Vn1wG4jPpZWLEkDO51jZgtm0k',
    appId: '1:37606563236:ios:537088de68095d7c1bf531',
    messagingSenderId: '37606563236',
    projectId: 'movieflix-dc21d',
    storageBucket: 'movieflix-dc21d.appspot.com',
    iosClientId: '37606563236-fbuba6f0r5pck068pegsh40p6g1o2j0m.apps.googleusercontent.com',
    iosBundleId: 'com.example.movieflix.RunnerTests',
  );
}
